grammar awfootnote
    document        <-  (footnote / content)*
    content         <-  (!footnote .)+
    footnote        <-  "awfootnote:" block_id:id "[" parameter_list "]" %store_footnote
    id              <-  [^\[]+
    parameter_list  <-  textParameter / refIdParameter
    refIdParameter  <-  "refid=" quote ref_id:refid quote %get_ref_id
    textParameter   <- (!refIdParameter [^\]])+ %get_text_parameter
    refid           <- [^\']+
    quote           <-  [\']



